declare const Neutralino: any
declare const NL_APPID: string
declare const NL_PORT: string
declare const NL_OS: string
declare const NL_VERSION: string
declare const NL_CVERSION: string
declare const NL_MODE: string
declare const NL_PID: string
declare const NL_ARGS: string[]
declare const NL_APPVERSION: string
