name: Publish Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: windows-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@master
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn
      - name: Get neutralino.js
        run: npx neu update
      - name: Build
        run: yarn run build
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: './dist'
          filename: '${{ github.event.repository.name }}.zip'
          path: ${{ github.event.repository.name }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './dist/${{ github.event.repository.name }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
